# Information Presentation & Data Visualisation

## 03 Lab Exercise sheet: Data abstraction

This lab focuses on practising the selection of appropriate data visualisations in Python by matching them to specific task abstractions. For examples, see: https://altair-viz.github.io/gallery/index.html

## Task 1: Import libraries and load datasets

In [22]:
import altair as alt
import pandas as pd

from vega_datasets import data

## Task 2: Create a scatter plot

a) Create a scatter plot using the "cars" dataset to visualise the relationship between "Horsepower" and "Miles Per Gallon. Set the colour of the points to a specific RGB triplet (e.g.,'rgb(255, 0, 0)' for red).

In [23]:
#setup
cars = data.cars()

#find the table details
cars.head(10)

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,1970-01-01,USA
6,chevrolet impala,14.0,8,454.0,220.0,4354,9.0,1970-01-01,USA
7,plymouth fury iii,14.0,8,440.0,215.0,4312,8.5,1970-01-01,USA
8,pontiac catalina,14.0,8,455.0,225.0,4425,10.0,1970-01-01,USA
9,amc ambassador dpl,15.0,8,390.0,190.0,3850,8.5,1970-01-01,USA

In [21]:
#scatter plot of
cars_scatter = alt.Chart(cars).mark_point(filled=True).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color = 'Origin',
    #tooltip to show the car's name when point hovered
    tooltip = 'Name'
).properties(
    title = 'Scatter Plot of Horsepower vs Miles Per Gallon'
)

cars_scatter

alt.Chart(...)

## Task 3: Create a line plot

a) Create a line plot to visualise the trend of maximum temperature over time in the "seattle_weather" dataset. Set the background to "grey" and the lines to "black".

In [56]:
#setup
seattle_weather = data.seattle_weather()


#find the table details
seattle_weather.head(10)

        date  precipitation  temp_max  temp_min  wind  weather
0 2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 2012-01-02           10.9      10.6       2.8   4.5     rain
2 2012-01-03            0.8      11.7       7.2   2.3     rain
3 2012-01-04           20.3      12.2       5.6   4.7     rain
4 2012-01-05            1.3       8.9       2.8   6.1     rain
5 2012-01-06            2.5       4.4       2.2   2.2     rain
6 2012-01-07            0.0       7.2       2.8   2.3     rain
7 2012-01-08            0.0      10.0       2.8   2.0      sun
8 2012-01-09            4.3       9.4       5.0   3.4     rain
9 2012-01-10            1.0       6.1       0.6   3.4     rain

In [42]:
#line graping the above weather
seattle_weather_line = alt.Chart(seattle_weather).mark_line().encode(
    x = alt.X('date', axis=alt.Axis(gridColor='black')),
    y = alt.Y('temp_max', axis=alt.Axis(gridColor='black')),
    color = 'weather',
    tooltip = 'date'
).properties(
    background = 'lightgrey'
)

seattle_weather_line

alt.Chart(...)

## Task 4: Create a bar chart

Create a bar chart to visualise the distribution of population across different age groups in the "population" dataset.

In [46]:
#setup
population = data.population()

#find the table details
population.head(10)

   year  age  sex   people
0  1850    0    1  1483789
1  1850    0    2  1450376
2  1850    5    1  1411067
3  1850    5    2  1359668
4  1850   10    1  1260099
5  1850   10    2  1216114
6  1850   15    1  1077133
7  1850   15    2  1110619
8  1850   20    1  1017281
9  1850   20    2  1003841

In [59]:
#plottig a bar chart of population
population_bar = alt.Chart(population).mark_bar().encode(
    alt.X('age:O'),
    alt.Y('people:Q'),
    color = 'year',
    tooltip = 'year'
)

population_bar

alt.Chart(...)

## Task 5:  Create a stacked bar chart

Create a stacked bar chart to visualise the contribution of different energy sources (e.g., fossil, renewables) to the total net electricity generation in Iowa (dataset: "iowa_electricity") over time.

In [67]:
#setup
iowa_electricity = data.iowa_electricity()

#find the table details
iowa_electricity.head(10)

        year        source  net_generation
0 2001-01-01  Fossil Fuels           35361
1 2002-01-01  Fossil Fuels           35991
2 2003-01-01  Fossil Fuels           36234
3 2004-01-01  Fossil Fuels           36205
4 2005-01-01  Fossil Fuels           36883
5 2006-01-01  Fossil Fuels           37014
6 2007-01-01  Fossil Fuels           41389
7 2008-01-01  Fossil Fuels           42734
8 2009-01-01  Fossil Fuels           38620
9 2010-01-01  Fossil Fuels           42750

In [65]:
#stacked bar charting
iowa_electricity_stacked = alt.Chart(iowa_electricity).mark_bar().encode(
    x = alt.X('year:O'),
    y = alt.Y('sum(net_generation):Q'),
    color = 'source:N'
    #tooltip = ['year:O', 'source:N', 'sum(net_generation):Q']
)

iowa_electricity_stacked

alt.Chart(...)

## Task 6: Create a streamgraph

Create a streamgraph to visualise the changing proportions of unemployment across the "Education and Health" and "Information" sectors over time using the "unemployment_across_industries" dataset.

In [68]:
#setup
unemployment_across_industries = data.unemployment_across_industries()

#find the table details
unemployment_across_industries.head(10)

       series  year  month  count  rate                      date
0  Government  2000      1    430   2.1 2000-01-01 08:00:00+00:00
1  Government  2000      2    409   2.0 2000-02-01 08:00:00+00:00
2  Government  2000      3    311   1.5 2000-03-01 08:00:00+00:00
3  Government  2000      4    269   1.3 2000-04-01 08:00:00+00:00
4  Government  2000      5    370   1.9 2000-05-01 07:00:00+00:00
5  Government  2000      6    603   3.1 2000-06-01 07:00:00+00:00
6  Government  2000      7    545   2.9 2000-07-01 07:00:00+00:00
7  Government  2000      8    583   3.1 2000-08-01 07:00:00+00:00
8  Government  2000      9    408   2.1 2000-09-01 07:00:00+00:00
9  Government  2000     10    391   2.0 2000-10-01 07:00:00+00:00

In [80]:
#streamgraph of unemployment for specific sectors
unemployment_stream = alt.Chart(unemployment_across_industries).transform_filter(
    alt.FieldOneOfPredicate(field='series', oneOf=['Education and Health', 'Information'])
).mark_area().encode(
    alt.X('date:T'),
    alt.Y('rate:Q', stack='center'),
    alt.Color('series:N'),
    tooltip = ['rate', 'date']
)

unemployment_stream

alt.Chart(...)

## Task 7: Create an indexed line chart

Create an indexed line chart to visualise the relative price movements of different stocks over time using the "stocks" dataset.

In [81]:
#setup
stocks = data.stocks()

#find the table details
stocks.head(10)

  symbol       date  price
0   MSFT 2000-01-01  39.81
1   MSFT 2000-02-01  36.35
2   MSFT 2000-03-01  43.22
3   MSFT 2000-04-01  28.37
4   MSFT 2000-05-01  25.45
5   MSFT 2000-06-01  32.54
6   MSFT 2000-07-01  28.40
7   MSFT 2000-08-01  28.40
8   MSFT 2000-09-01  24.53
9   MSFT 2000-10-01  28.02

In [90]:
#line chart for stock price movement
stocks_line = alt.Chart(stocks).mark_line(strokeWidth = 3).encode(
    alt.X('date:T'),
    alt.Y('price:Q'),
    alt.Color('symbol:N'),
    tooltip = 'price'
)

stocks_line

alt.Chart(...)

## Task 7: Create a heatmap

Create a heatmap to visualise the relationship between flight distance and average arrival delay in the "flights_5k" dataset. Try out different colour schemes.

In [91]:
#setup
flights = data.flights_5k()

#find the table details
flights.head(10)

                 date  delay  distance origin destination
0 2001-01-10 18:20:00     25       192    SAT         HOU
1 2001-01-31 16:45:00     17       371    SNA         OAK
2 2001-02-16 12:07:00     21       417    SJC         SAN
3 2001-02-03 17:00:00     -5       480    SMF         SAN
4 2001-01-02 12:16:00      5       833    OKC         PHX
5 2001-01-02 10:12:00      5       601    PHX         RNO
6 2001-02-27 21:35:00     10       462    OKC         STL
7 2001-01-16 12:33:00      8       323    BHM         SDF
8 2001-03-26 21:20:00     65       423    MDW         OMA
9 2001-03-30 15:42:00      9       237    TUL         DAL

In [111]:
#heatmapping flight distance and arrival delay
delay_distance_heatmap = alt.Chart(flights).mark_rect().encode(
    alt.Y('distance:Q').bin(maxbins=30),
    alt.X('delay:Q').bin(maxbins=50),
    alt.Color('count()').scale(scheme='greenblue'),
    tooltip = ['count()']
)

#putting a veritcal line to show where delays and early leaves seperate
zero_delay_line = alt.Chart(pd.DataFrame({'delay': [0]})).mark_rule(
    color='red',
    strokeWidth=2
    ).encode(
    x='delay'
)

alt.layer(delay_distance_heatmap, zero_delay_line)

alt.LayerChart(...)

## Task 8: Create a parallel coordinates plot

Create a parallel coordinates plot to visualise the relationships between sepal length, sepal width, petal length, and petal width for different species of Iris flowers in the "iris" dataset.

In [103]:
#setup
iris = data.iris()

#find the table details
iris.head(10)

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

In [118]:
#coordinates parallel of iris dataset
iris_parallel = alt.Chart(iris, width = 500).transform_window(
    index='count()'
).transform_fold(
    ['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth']
).mark_line().encode(
    x = 'key:N',
    y = 'value:Q',
    color = 'species:N',
    detail = 'index:N',
    tooltip = 'value:Q',
    opacity=alt.value(0.5)
)

iris_parallel

alt.Chart(...)

## Task 9: Create a pie chart

Create a pie chart to visualise the distribution of cars based on their country of origin in the "cars" dataset.

In [119]:
#setup already done
#pie chart of car distribution by country
cars_pie = alt.Chart(cars).mark_arc().encode(
    theta = 'count()',
    color = 'Origin',
    tooltip = 'Origin'
)

cars_pie

alt.Chart(...)

### Worksheets should be submitted on Canvas by the Monday after the lab at 23:59.